name: Creación de Nuevo Cliente

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificación
        run: echo "Se ha creado un nuevo cliente. Información enviada al equipo."
