name: Solicitud de Nuevas Funciones

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  nuevas-funciones:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'nueva funcionalidad')
    steps:
      - name: Notificar Solicitud de Nueva Funcionalidad
        run: echo "Se ha solicitado una nueva funcionalidad. Revisar la issue #${{ github.event.issue.number }}."
